### ISSUE TITLE
Minislate only works on linux hosts

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/minislate#56]
Right now the following requires a Linux host due to the bind mounts present in `docker-compose.yml.tmpl`.

```yaml
kube:
    image: rancher/k3s:v1.19.5-k3s1-amd64
    restart: always
    tty: true
    privileged: true
    command: server --https-listen-port 6443 --kube-apiserver-arg service-node-port-range=30000-30100
    volumes:
      - /lib/modules:/lib/modules                       # !bind mount!
      - kubernetes:/etc/rancher
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                # !bind mount!
    ports:
      - 30000-30100:30000-30100
```

Re-tool to work on any host operating system.
